// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebpackBundleInfo;

namespace WebpackBundleInfo.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20210702110639_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.7")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("WebpackBundleInfo.Bundles.Bundle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CommitSha")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTimeOffset>("CommitTimestamp")
                        .HasColumnType("datetimeoffset");

                    b.Property<long>("TotalGzipSize")
                        .HasColumnType("bigint");

                    b.Property<long>("TotalParsedSize")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("CommitSha")
                        .IsUnique();

                    b.ToTable("Bundles");
                });

            modelBuilder.Entity("WebpackBundleInfo.Bundles.Bundle", b =>
                {
                    b.OwnsMany("WebpackBundleInfo.Bundles.BundleComponent", "Components", b1 =>
                        {
                            b1.Property<int>("BundleId")
                                .HasColumnType("int");

                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("int")
                                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                            b1.Property<long>("GzipSize")
                                .HasColumnType("bigint");

                            b1.Property<string>("Label")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<long>("ParsedSize")
                                .HasColumnType("bigint");

                            b1.Property<long>("StatSize")
                                .HasColumnType("bigint");

                            b1.HasKey("BundleId", "Id");

                            b1.ToTable("BundleComponents");

                            b1.WithOwner()
                                .HasForeignKey("BundleId");
                        });

                    b.Navigation("Components");
                });
#pragma warning restore 612, 618
        }
    }
}
